### PR TITLE
ci(github): build via actions

### PR DESCRIPTION
**Pull request by ybiquitous**

### CODE REVIEW

**Comment by ybiquitous** [comment]
There is no alternative to `commitlint-travis` yet.

**Comment by ybiquitous** [comment]
See https://github.com/conventional-changelog/commitlint/issues/586

**Comment by wagoid** [comment]
Hey @ybiquitous! In  case you still want to run commitlint via github actions, I've created this one that does the job: https://github.com/marketplace/actions/commit-linter

**Comment by ybiquitous** [comment]
@wagoid Thank you! I'll try it later. 😉

**Pull request closed without merging**
